name: deploy
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - if: github.event.release
        name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - if: github.event.release
        name: Setup Scala
        uses: olafurpg/setup-scala@v13
      - if: github.event.release
        name: Deploy (release only)
        run: sbt test