name: Check PR
on:
  pull_request:
    branches: ['*']
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
      - name: Run unit tests
        run: sbt test